### ISSUE TITLE
Html5 | 我准备起飞

### ISSUE THREAD

**Issue by jiqiangzhu** [jiqiangzhu/jiqiangzhu.github.io#40]
https://jiqiangzhu.github.io/basic/flex.html 

 起飞！唉~飞

**Comment by blairq-coding** [comment]
非常好

**Comment by blairq-coding** [comment]
```css
/*flex居中的一种方法*/
  .flex {
    display: flex;
    justify-content: center;
    align-items: center;
  }
```
